const ShopActionTypes = {
    LOAD_PRODUCTS : 'LOAD_PRODUCTS',
    LOAD_CATEGORIES : 'LOAD_CATEGORIES',
    SET_CATEGORY : 'SET_CATEGORY',
    SHOW_CART : 'SHOW_CART',
    HIDE_CART : 'HIDE_CART',
    SHOW_MODAL : 'SHOW_MODAL',
    HIDE_MODAL : 'HIDE_MODAL',
    LOAD_PAGE  : 'LOAD_PAGE'
}

export default ShopActionTypes; 